sudo: false
language: python
python:
  - "3.5"
  - "3.6"
cache:
  pip: true
env:
  - DJANGO_VERSION=2.0.8
  - DJANGO_VERSION=2.1.1
install:
    - pip install -q psycopg2 Pillow django-request-id requests django==$DJANGO_VERSION
    - pip install flake8 codecov coverage
script:
    - flake8 binder
    - coverage run --include="binder/*" setup.py test
before_script:
  - psql -c 'create database "binder-test";' -U postgres
  - export CY_RUNNING_INSIDE_TRAVIS=1
services:
  - postgresql
addons:
  postgresql: "9.6"
after_success:
    - codecov
