sudo: false
language: python
python:
  - "3.4"
  - "3.5"
cache:
  pip: true
install:
    - ./setup.py install
    - pip install flake8 codecov coverage
script:
    - flake8 binder
    - coverage run --include="binder/*" setup.py test
before_script:
  - psql -c 'create database "binder-test";' -U postgres
services:
  - postgresql
addons:
  postgresql: "9.5"
after_success:
    - codecov
